from app.schemas.untis_xml import (
    UntisGeneralInfo,
    UntisTimePeriod,
    UntisTeacher,
    UntisSubject,
    UntisRoom,
    UntisClass,
    UntisStudent,
    UntisLessonTime,
    UntisLesson,
    UntisParsedDataset,
)
from app.schemas.arbor_payloads import (
    ArborTeachingGroupCreate,
    ArborTeachingGroupResponse,
    ArborTimetableSlot,
    ArborSessionCreate,
    ArborSessionResponse,
    ArborStudentGroupEnrollment,
)
from app.schemas.bromcom_payloads import (
    BromcomClassCreate,
    BromcomClassResponse,
    BromcomTimetableSlot,
    BromcomScheduleAssignment,
    BromcomCurriculumEnrollment,
)
from app.schemas.quarantine import (
    QuarantineItemCreate,
    QuarantineResolutionPayload,
    QuarantineItemResponse,
    QuarantineSummaryStats,
)

__all__ = [
    "UntisGeneralInfo",
    "UntisTimePeriod",
    "UntisTeacher",
    "UntisSubject",
    "UntisRoom",
    "UntisClass",
    "UntisStudent",
    "UntisLessonTime",
    "UntisLesson",
    "UntisParsedDataset",
    "ArborTeachingGroupCreate",
    "ArborTeachingGroupResponse",
    "ArborTimetableSlot",
    "ArborSessionCreate",
    "ArborSessionResponse",
    "ArborStudentGroupEnrollment",
    "BromcomClassCreate",
    "BromcomClassResponse",
    "BromcomTimetableSlot",
    "BromcomScheduleAssignment",
    "BromcomCurriculumEnrollment",
    "QuarantineItemCreate",
    "QuarantineResolutionPayload",
    "QuarantineItemResponse",
    "QuarantineSummaryStats",
]