<?xml version="1.0" encoding="utf-8"?>

<xs:schema id="XmlInterfaceSchema"
    version="3.8"
    targetNamespace="https://untis.at/untis/XmlInterface"
    elementFormDefault="qualified"
    xmlns="https://untis.at/untis/XmlInterface"
    xmlns:mstns="https://untis.at/untis/XmlInterface"
    xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="document" type="XmlDocument" />

    <xs:complexType name="XmlDocument">
        <xs:all>
            <xs:element name="general" type="XmlGeneralSettings" minOccurs="1" maxOccurs="1" />
            <xs:element name="timeperiods" type="XmlTimegridInformation" minOccurs="1" maxOccurs="1" />
            <xs:element name="holidays" type="XmlHolidayList" minOccurs="1" maxOccurs="1" />
            <xs:element name="descriptions" type="XmlDescriptionList" minOccurs="1" maxOccurs="1" />
            <xs:element name="departments" type="XmlDepartmentList" minOccurs="1" maxOccurs="1" />
            <xs:element name="rooms" type="XmlRoomList" minOccurs="1" maxOccurs="1" />
            <xs:element name="roomgroups" type="XmlRoomGroupList" minOccurs="0" maxOccurs="1" />
            <xs:element name="subjects" type="XmlSubjectList" minOccurs="1" maxOccurs="1" />
            <xs:element name="teachers" type="XmlTeacherList" minOccurs="1" maxOccurs="1" />
            <xs:element name="classes" type="XmlClassList" minOccurs="1" maxOccurs="1" />
            <xs:element name="students" type="XmlStudentList" minOccurs="1" maxOccurs="1" />
            <xs:element name="studentgroups" type="XmlStudentGroupList" minOccurs="1" maxOccurs="1" />
            <xs:element name="lesson_date_schemes" type="XmlLessonDateSchemeList" minOccurs="1" maxOccurs="1" />
            <xs:element name="lessons" type="XmlLessonList" minOccurs="1" maxOccurs="1" />
            <xs:element name="reductions" type="XmlReductionList" minOccurs="1" maxOccurs="1" />
            <xs:element name="reduction_reasons" type="XmlReductionReasonList" minOccurs="1" maxOccurs="1" />
            <xs:element name="lesson_tables" type="XmlLessonsTableList" minOccurs="1" maxOccurs="1" />
            <xs:element name="extensions" type="XmlExtensionList" minOccurs="0" maxOccurs="1" />
        </xs:all>
        <xs:attribute name="version" type="XmlFormatVersion" use="required" />
        <xs:attribute name="date" type="XmlDate" use="required" />
        <xs:attribute name="time" type="XmlTimeHHMMSS" use="required" />
    </xs:complexType>


    <!-- GENERAL INFORMATION -->
    
    <xs:complexType name="XmlGeneralSettings">
        <xs:all>
            <xs:element name="schoolname" type="xs:string" minOccurs="1" maxOccurs="1" />
            <xs:element name="schoolnumber" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="schooltype" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="schoolyearbegindate" type="XmlDate" minOccurs="1" maxOccurs="1" />
            <xs:element name="schoolyearenddate" type="XmlDate" minOccurs="1" maxOccurs="1" />
            <xs:element name="header1" type="xs:string" minOccurs="1" maxOccurs="1" />
            <xs:element name="header2" type="xs:string" minOccurs="1" maxOccurs="1" />
            <xs:element name="footer" type="xs:string" minOccurs="1" maxOccurs="1" />
            <xs:element name="termbegindate" type="XmlDate" minOccurs="1" maxOccurs="1" />
            <xs:element name="termenddate" type="XmlDate" minOccurs="1" maxOccurs="1" />
            <xs:element name="termname" type="xs:string" minOccurs="1" maxOccurs="1" />
            <xs:element name="week_periodicity" type="xs:int" minOccurs="0" maxOccurs="1" />
        </xs:all>
    </xs:complexType>


    <!-- TIMEGRID INFORMATION -->

    <xs:complexType name="XmlTimegridInformation">
        <xs:sequence>
            <xs:element name="timeperiod" type="XmlTimegridSlot" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="XmlTimegridSlot">
        <xs:all>
            <xs:element name="day" type="xs:int" minOccurs="1" maxOccurs="1" />
            <xs:element name="period" type="xs:int" minOccurs="1" maxOccurs="1" />
            <xs:element name="starttime" type="XmlTime" minOccurs="1" maxOccurs="1" />
            <xs:element name="endtime" type="XmlTime" minOccurs="1" maxOccurs="1" />
            <xs:element name="label" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="foreignkey" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="timegrid" type="xs:string" minOccurs="0" maxOccurs="1" />
        </xs:all>
        <xs:attribute name="id" type="xs:string" use="required" />
    </xs:complexType>

    <!-- HOLIDAY INFORMATION -->

    <xs:complexType name="XmlHolidayList">
        <xs:sequence>
            <xs:element name="holiday" type="XmlHoliday" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>


    <!-- ELEMENT LISTS -->

    <xs:complexType name="XmlDescriptionList">
        <xs:sequence>
            <xs:element name="description" type="XmlDescription" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="XmlDepartmentList">
        <xs:sequence>
            <xs:element name="department" type="XmlDepartment" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="XmlRoomList">
        <xs:sequence>
            <xs:element name="room" type="XmlRoom" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="XmlRoomGroupList">
       <xs:sequence>
           <xs:element name="roomgroup" type="XmlRoomGroup" minOccurs="0" maxOccurs="unbounded" />
       </xs:sequence>
    </xs:complexType>

    <xs:complexType name="XmlSubjectList">
        <xs:sequence>
            <xs:element name="subject" type="XmlSubject" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="XmlTeacherList">
        <xs:sequence>
            <xs:element name="teacher" type="XmlTeacher" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="XmlClassList">
        <xs:sequence>
            <xs:element name="class" type="XmlClass" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="XmlStudentList">
        <xs:sequence>
            <xs:element name="student" type="XmlStudent" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="XmlStudentGroupList">
        <xs:sequence>
            <xs:element name="studentgroup" type="XmlStudentGroup" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="XmlLessonDateSchemeList">
        <xs:sequence>
            <xs:element name="lesson_date_scheme" type="XmlLessonDateScheme" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="XmlReductionReasonList">
        <xs:sequence>
            <xs:element name="reduction_reason" type="XmlReductionReason" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <!-- FOR FUTURE USE / FOR CUSTOMIZATION -->
    <xs:complexType name="XmlExtensionList">
        <xs:sequence>
            <xs:element name="type" type="xs:string" minOccurs="1" maxOccurs="1" />
        </xs:sequence>
    </xs:complexType>


    <!-- ELEMENT TYPES -->

    <!-- 
    Note: The reason why common elements like `longname` or `forecolor` are not in the `XmlBaseElement` type is 
    that the <xs:all> content type is not extensible. Thats just how XSD works.
    -->
    <xs:complexType name="XmlBaseElement">
        <xs:attribute name="id" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="XmlBaseElementReference">
        <xs:attribute name="id" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="XmlHoliday">
        <xs:complexContent>
            <xs:extension base="XmlBaseElement">
                <xs:all>
                    <xs:element name="type" type="XmlHolidayType" minOccurs="1" maxOccurs="1" />
                    <xs:element name="longname" type="xs:string" minOccurs="1" maxOccurs="1" />
                    <xs:element name="starttime" type="XmlDate" minOccurs="1" maxOccurs="1" />
                    <xs:element name="endtime" type="XmlDate" minOccurs="1" maxOccurs="1" />
                </xs:all>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>


    <xs:complexType name="XmlDescription">
        <xs:complexContent>
            <xs:extension base="XmlBaseElement">
                <xs:all>
                    <xs:element name="longname" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="forecolor" type="XmlHexColor" minOccurs="0" maxOccurs="1" />
                    <xs:element name="backcolor" type="XmlHexColor" minOccurs="0" maxOccurs="1" />
                    <xs:element name="flags" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="foreignkey" type="xs:string" minOccurs="0" maxOccurs="1" />
                </xs:all>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="XmlDepartment">
        <xs:complexContent>
            <xs:extension base="XmlBaseElement">
                <xs:all>
                    <xs:element name="longname" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="forecolor" type="XmlHexColor" minOccurs="0" maxOccurs="1" />
                    <xs:element name="backcolor" type="XmlHexColor" minOccurs="0" maxOccurs="1" />
                    <xs:element name="foreignkey" type="xs:string" minOccurs="0" maxOccurs="1" />
                </xs:all>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="XmlRoom">
        <xs:complexContent>
            <xs:extension base="XmlBaseElement">
                <xs:all>
                    <xs:element name="longname" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="forecolor" type="XmlHexColor" minOccurs="0" maxOccurs="1" />
                    <xs:element name="backcolor" type="XmlHexColor" minOccurs="0" maxOccurs="1" />
                    <xs:element name="room_description" type="XmlBaseElementReference" minOccurs="0" maxOccurs="1" />
                    <xs:element name="room_department" type="XmlBaseElementReference" minOccurs="0" maxOccurs="1" />
                    <xs:element name="text" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="foreignkey" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="external_name" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="capacity" type="xs:int" minOccurs="0" maxOccurs="1" />
                    <xs:element name="flags" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="roomgroups" type="XmlBaseElementReference" minOccurs="0" maxOccurs="1" />
                </xs:all>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="XmlRoomGroup">
      <xs:complexContent>
        <xs:extension base="XmlBaseElement">
          <xs:all>
            <xs:element name="longname" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="rooms" minOccurs="1" maxOccurs="1">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="room" type="XmlBaseElementReference" minOccurs="0" maxOccurs="unbounded" />
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="forecolor" type="XmlHexColor" minOccurs="0" maxOccurs="1" />
            <xs:element name="backcolor" type="XmlHexColor" minOccurs="0" maxOccurs="1" />
            <xs:element name="foreignkey" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="foreigndata" type="xs:string" minOccurs="0" maxOccurs="1" />
          </xs:all>
        </xs:extension>
      </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="XmlSubject">
        <xs:complexContent>
            <xs:extension base="XmlBaseElement">
                <xs:all>
                    <xs:element name="longname" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="alias" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="forecolor" type="XmlHexColor" minOccurs="0" maxOccurs="1" />
                    <xs:element name="backcolor" type="XmlHexColor" minOccurs="0" maxOccurs="1" />
                    <xs:element name="subjectgroup" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="text" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="flags" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="subject_room" type="XmlBaseElementReference" minOccurs="0" maxOccurs="1" />
                    <xs:element name="subject_description" type="XmlBaseElementReference" minOccurs="0" maxOccurs="1" />
                    <xs:element name="subject_department" type="XmlBaseElementReference" minOccurs="0" maxOccurs="1" />
                    <xs:element name="foreignkey" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="foreigndata" type="xs:string" minOccurs="0" maxOccurs="1" />
                </xs:all>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>


    <xs:complexType name="XmlTeacher">
        <xs:complexContent>
            <xs:extension base="XmlBaseElement">
                <xs:all>
                    <xs:element name="longname" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="alias" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="forename" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="surname" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="title" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="gender" type="XmlGender" minOccurs="0" maxOccurs="1" />
                    <xs:element name="birthdate" type="XmlDate" minOccurs="0" maxOccurs="1" />
                    <xs:element name="status" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="email" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="phone" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="forecolor" type="XmlHexColor" minOccurs="0" maxOccurs="1" />
                    <xs:element name="backcolor" type="XmlHexColor" minOccurs="0" maxOccurs="1" />
                    <xs:element name="text" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="text2" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="flags" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="payrollnumber" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="teacher_description" type="XmlBaseElementReference" minOccurs="0" maxOccurs="1" />
                    <xs:element name="teacher_department" type="XmlBaseElementReference" minOccurs="0" maxOccurs="1" />
                    <xs:element name="teacher_room" type="XmlBaseElementReference" minOccurs="0" maxOccurs="1" />
                    <xs:element name="teacher_qualifications" type="XmlTeacherQualificationList" minOccurs="0" maxOccurs="1" />
                    <xs:element name="foreignkey" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="external_name" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="weektarget" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="personnel_number_2" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="cellphonenumber" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="entry_date" type="XmlDate" minOccurs="0" maxOccurs="1" />
                    <xs:element name="exit_date" type="XmlDate" minOccurs="0" maxOccurs="1" />
                    <xs:element name="main_school" minOccurs="0" maxOccurs="1">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:maxLength value="20"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:element>
                    <xs:element name="extensions" type="XmlExtensionListTeacher" minOccurs="0" maxOccurs="1" />
					<xs:element name="salutation" type="xs:string" minOccurs="0" maxOccurs="1" />
                </xs:all>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="XmlClass">
        <xs:complexContent>
            <xs:extension base="XmlBaseElement">
                <xs:all>
                    <xs:element name="longname" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="alias" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="forecolor" type="XmlHexColor" minOccurs="0" maxOccurs="1" />
                    <xs:element name="backcolor" type="XmlHexColor" minOccurs="0" maxOccurs="1" />
                    <xs:element name="text" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="class_room" type="XmlBaseElementReference" minOccurs="0" maxOccurs="1" />
                    <xs:element name="class_department" type="XmlBaseElementReference" minOccurs="0" maxOccurs="1" />
                    <xs:element name="class_description" type="XmlBaseElementReference" minOccurs="0" maxOccurs="1" />
                    <xs:element name="class_teacher" type="XmlBaseElementReference" minOccurs="0" maxOccurs="1" />
                    <xs:element name="lessonstable" type="XmlBaseElementReference" minOccurs="0" maxOccurs="1" />
                    <xs:element name="studentsmale" type="xs:int" minOccurs="0" maxOccurs="1" />
                    <xs:element name="studentsfemale" type="xs:int" minOccurs="0" maxOccurs="1" />
                    <xs:element name="flags" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="classlevel" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="begindate" type="XmlDate" minOccurs="0" maxOccurs="1" />
                    <xs:element name="enddate" type="XmlDate" minOccurs="0" maxOccurs="1" />
                    <xs:element name="foreignkey" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="external_name" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="timegrid" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="class_group_number" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="master_class" type="xs:string" minOccurs="0" maxOccurs="1" />                    
                </xs:all>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="XmlStudent">
        <xs:complexContent>
            <xs:extension base="XmlBaseElement">
                <xs:all>
                    <xs:element name="longname" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="forename" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="surname" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="gender" type="XmlGender" minOccurs="0" maxOccurs="1" />
                    <xs:element name="birthdate" type="XmlDate" minOccurs="0" maxOccurs="1" />
                    <xs:element name="idnumber" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="email" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="student_class" type="XmlBaseElementReference" minOccurs="0" maxOccurs="1" />
                    <xs:element name="student_description" type="XmlBaseElementReference" minOccurs="0" maxOccurs="1" />
                    <xs:element name="forecolor" type="XmlHexColor" minOccurs="0" maxOccurs="1" />
                    <xs:element name="backcolor" type="XmlHexColor" minOccurs="0" maxOccurs="1" />
                    <xs:element name="foreignkey" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="text" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="flags" type="xs:string" minOccurs="0" maxOccurs="1" />
                </xs:all>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="XmlStudentGroup">
        <xs:complexContent>
            <xs:extension base="XmlBaseElement">
                <xs:all>
                    <xs:element name="longname" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="classes" minOccurs="1" maxOccurs="1">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="class" type="XmlBaseElementReference" minOccurs="0" maxOccurs="unbounded" />
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                    <xs:element name="subject" type="XmlBaseElementReference" minOccurs="0" maxOccurs="1" />
                    <xs:element name="forecolor" type="XmlHexColor" minOccurs="0" maxOccurs="1" />
                    <xs:element name="backcolor" type="XmlHexColor" minOccurs="0" maxOccurs="1" />
                </xs:all>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="XmlLessonDateScheme">
        <xs:complexContent>
            <xs:extension base="XmlBaseElement">
                <xs:all>
                    <xs:element name="longname" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="date_scheme" type="XmlDateScheme" minOccurs="1" maxOccurs="1" />
                    <xs:element name="periodic_weeks" type="XmlPeriodicWeeks" minOccurs="1" maxOccurs="1" />
                </xs:all>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="XmlReductionReason">
        <xs:complexContent>
            <xs:extension base="XmlBaseElement">
                <xs:all>
                    <xs:element name="longname" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="forecolor" type="XmlHexColor" minOccurs="0" maxOccurs="1" />
                    <xs:element name="backcolor" type="XmlHexColor" minOccurs="0" maxOccurs="1" />
                    <xs:element name="text" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="reduction_description" type="xs:string" minOccurs="0" maxOccurs="1" />
                </xs:all>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>


    <!-- PERIODIC WEEKS -->
    
    <xs:complexType name="XmlPeriodicWeeks">
        <xs:all>
            <xs:element name="WeekA" type="xs:string" fixed="" minOccurs="0" maxOccurs="1" />
            <xs:element name="WeekB" type="xs:string" fixed="" minOccurs="0" maxOccurs="1" />
            <xs:element name="WeekC" type="xs:string" fixed="" minOccurs="0" maxOccurs="1" />
            <xs:element name="WeekD" type="xs:string" fixed="" minOccurs="0" maxOccurs="1" />
            <xs:element name="WeekE" type="xs:string" fixed="" minOccurs="0" maxOccurs="1" />
            <xs:element name="WeekF" type="xs:string" fixed="" minOccurs="0" maxOccurs="1" />
            <xs:element name="WeekG" type="xs:string" fixed="" minOccurs="0" maxOccurs="1" />
            <xs:element name="WeekH" type="xs:string" fixed="" minOccurs="0" maxOccurs="1" />
            <xs:element name="WeekI" type="xs:string" fixed="" minOccurs="0" maxOccurs="1" />
            <xs:element name="WeekJ" type="xs:string" fixed="" minOccurs="0" maxOccurs="1" />
            <xs:element name="WeekK" type="xs:string" fixed="" minOccurs="0" maxOccurs="1" />
            <xs:element name="WeekL" type="xs:string" fixed="" minOccurs="0" maxOccurs="1" />
            <xs:element name="WeekM" type="xs:string" fixed="" minOccurs="0" maxOccurs="1" />
            <xs:element name="WeekN" type="xs:string" fixed="" minOccurs="0" maxOccurs="1" />
            <xs:element name="WeekO" type="xs:string" fixed="" minOccurs="0" maxOccurs="1" />
            <xs:element name="WeekP" type="xs:string" fixed="" minOccurs="0" maxOccurs="1" />
        </xs:all>
    </xs:complexType>
    
    <!-- LESSONS TABLE -->

    <xs:complexType name="XmlLessonsTableList">
        <xs:sequence>
            <xs:element name="lesson_table" type="XmlLessonsTable" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="XmlLessonsTable">
        <xs:complexContent>
            <xs:extension base="XmlBaseElement">
                <xs:all>
                    <xs:element name="longname" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="forecolor" type="XmlHexColor" minOccurs="0" maxOccurs="1" />
                    <xs:element name="backcolor" type="XmlHexColor" minOccurs="0" maxOccurs="1" />
                    <xs:element name="text" type="xs:string" minOccurs="0" maxOccurs="1" />
                    <xs:element name="lesson_table_subjects" type="XmlLessonsTableEntryList" minOccurs="1" maxOccurs="1" />
                </xs:all>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="XmlLessonsTableEntryList">
        <xs:sequence>
            <xs:element name="lesson_table_subject" type="XmlLessonsTableEntry" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="XmlLessonsTableEntry">
        <xs:attribute name="id" type="xs:string" use="required" />
        <xs:attribute name="min_periods" type="xs:int" use="optional" />
        <xs:attribute name="max_periods" type="xs:int" use="optional" />
    </xs:complexType>
    
    <!-- LESSONS -->

    <xs:complexType name="XmlLessonList">
        <xs:sequence>
            <xs:element name="lesson" type="XmlLesson" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="XmlLesson">
        <xs:all>
            <xs:element name="periods" type="xs:int" minOccurs="0" maxOccurs="1" />
            <xs:element name="yearly_periods" type="xs:int" minOccurs="0" maxOccurs="1" />
            <xs:element name="duration" type="XmlMinuteDuration" minOccurs="0" maxOccurs="1" />
            <xs:element name="lesson_teacher" type="XmlBaseElementReference" minOccurs="0" maxOccurs="1" />
            <xs:element name="lesson_subject" type="XmlBaseElementReference" minOccurs="0" maxOccurs="1" />
            <xs:element name="lesson_classes" type="XmlBaseElementReference" minOccurs="0" maxOccurs="1" />
            <xs:element name="lesson_studentgroups" type="XmlBaseElementReference" minOccurs="0" maxOccurs="1" />
            <xs:element name="lesson_date_scheme" type="XmlBaseElementReference" minOccurs="0" maxOccurs="1" />
            <xs:element name="teacher_value" type="xs:int" minOccurs="0" maxOccurs="1" />
            <xs:element name="begindate" type="XmlDate" minOccurs="0" maxOccurs="1" />
            <xs:element name="enddate" type="XmlDate" minOccurs="0" maxOccurs="1" />
            <xs:element name="effectivebegindate" type="XmlDate" minOccurs="1" maxOccurs="1" />
            <xs:element name="effectiveenddate" type="XmlDate" minOccurs="1" maxOccurs="1" />
            <xs:element name="block" type="XmlNumberArray" minOccurs="0" maxOccurs="1" />
            <xs:element name="week" type="XmlPeriodicWeek" minOccurs="0" maxOccurs="1" />
            <xs:element name="occurence" type="XmlDateScheme" minOccurs="1" maxOccurs="1" />
            <xs:element name="lesson_description" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="lesson_students" type="XmlBaseElementReference" minOccurs="0" maxOccurs="1" />
            <xs:element name="statcodes" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="teacher_statcode" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="forecolor" type="XmlHexColor" minOccurs="0" maxOccurs="1" />
            <xs:element name="backcolor" type="XmlHexColor" minOccurs="0" maxOccurs="1" />
            <xs:element name="text" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="text1" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="text2" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="flags" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="foreignkey" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="foreigndata" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="timegrid" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="times" type="XmlLessonTimes" minOccurs="1" maxOccurs="1" />
            <xs:element name="max_students" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="min_students" type="xs:string" minOccurs="0" maxOccurs="1" />
        </xs:all>
        <xs:attribute name="id" type="XmlLessonIdType" use="required" />
    </xs:complexType>

    <xs:complexType name="XmlLessonTimes">
        <xs:sequence>
            <xs:element name="time" type="XmlLessonTime" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="XmlLessonTime">
        <xs:all>
            <xs:element name="assigned_day" type="xs:int" minOccurs="1" maxOccurs="1" />
            <xs:element name="assigned_period" type="xs:int" minOccurs="0" maxOccurs="1" />
            <xs:element name="assigned_date" type="XmlDate" minOccurs="0" maxOccurs="1" />
            <xs:element name="assigned_starttime" type="XmlTime" minOccurs="1" maxOccurs="1" />
            <xs:element name="assigned_endtime" type="XmlTime" minOccurs="1" maxOccurs="1" />
            <xs:element name="assigned_room" type="XmlBaseElementReference" minOccurs="0" maxOccurs="1" />
        </xs:all>
    </xs:complexType>


    <!-- REDUCTIONS -->

    <xs:complexType name="XmlReductionList">
        <xs:sequence>
            <xs:element name="reduction" type="XmlReduction" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="XmlReduction">
        <xs:all>
            <xs:element name="reduction_teacher" type="xs:string" minOccurs="1" maxOccurs="1" />
            <xs:element name="value" type="xs:float" minOccurs="1" maxOccurs="1" />
            <xs:element name="reduction_reason" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="text" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="begindate" type="XmlDate" minOccurs="0" maxOccurs="1" />
            <xs:element name="enddate" type="XmlDate" minOccurs="0" maxOccurs="1" />
        </xs:all>
        <xs:attribute name="id" type="xs:string" use="required" />
    </xs:complexType>

    
    <!-- TEACHER QUALIFICATIONS -->

    <xs:complexType name="XmlTeacherQualificationList">
        <xs:sequence>
            <xs:element name="teacher_qualification" type="XmlTeacherQualification" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="XmlTeacherQualification">
        <xs:attribute name="subject" type="xs:string" use="required" />
        <xs:attribute name="from_level" type="xs:string" use="optional" />
        <xs:attribute name="to_level" type="xs:string" use="optional" />
    </xs:complexType>

    <!-- TEACHER EXTENSIONS - FOR CUSTOMIZATION -->

    <xs:complexType name="XmlExtensionListTeacher">
        <xs:sequence>
            <xs:element name="type" type="xs:string" minOccurs="1" maxOccurs="1" />
        </xs:sequence>
    </xs:complexType>


    <!-- PRIMITIVE TYPES -->

    <xs:simpleType name="XmlLessonIdType">
      <xs:restriction base="xs:string">
        <xs:pattern value="LS_[0-9]{3,}" />
      </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="XmlTime">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="0" />
            <xs:maxInclusive value="2359" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="XmlTimeHHMMSS">
        <xs:restriction base="xs:int">
            <xs:minInclusive value="0" />
            <xs:maxInclusive value="235959" />
        </xs:restriction>
    </xs:simpleType>

  <xs:simpleType name="XmlDate">
        <xs:restriction base="xs:int">
            <xs:totalDigits value="8" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="XmlHexColor">
        <xs:restriction base="xs:string">
            <xs:pattern value="#[0-9A-Fa-f]{6}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="XmlNumberArray">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9,]*" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="XmlDateScheme">
        <xs:restriction base="xs:string">
            <xs:pattern value="[01F]+" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="XmlGender">
        <xs:restriction base="xs:string">
            <xs:pattern value="[IMF]{1}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="XmlPeriodicWeek">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-P]+" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="XmlMinuteDuration">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]+:[0-9]{2}" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="XmlFormatVersion">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]+\.[0-9]+(-[0-9a-zA-Z]*)?" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="XmlHolidayType">
        <xs:restriction base="xs:string">
            <xs:pattern value="(Public holiday)|(School holidays)" />
        </xs:restriction>
    </xs:simpleType>

</xs:schema>
